name: uwb_platform_interface
description: A common platform interface for the uwb plugin.
version: 0.0.1
homepage: https://pub.dev/packages/uwb_platform_interface
repository: https://github.com/baseflow/flutter_uwb

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.2
  

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
