// Autogenerated from Pigeon (v3.1.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by MCNearbyServiceAdvertiserHostApi.
NSObject<FlutterMessageCodec> *MCNearbyServiceAdvertiserHostApiGetCodec(void);

@protocol MCNearbyServiceAdvertiserHostApi
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)checkPlatformCompatibilityWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void MCNearbyServiceAdvertiserHostApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<MCNearbyServiceAdvertiserHostApi> *_Nullable api);

NS_ASSUME_NONNULL_END
