// Autogenerated from Pigeon (v3.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, BFMCEncryptionPreferenceWrapper) {
  BFMCEncryptionPreferenceWrapperOptional = 0,
  BFMCEncryptionPreferenceWrapperRequired = 1,
  BFMCEncryptionPreferenceWrapperNone = 2,
};


/// The codec used by BFMCNearbyServiceAdvertiserDelegateFlutterApi.
NSObject<FlutterMessageCodec> *BFMCNearbyServiceAdvertiserDelegateFlutterApiGetCodec(void);

@interface BFMCNearbyServiceAdvertiserDelegateFlutterApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)didNotStartAdvertisingPeerWithCompletion:(void(^)(NSError *_Nullable))completion;
@end
/// The codec used by BFMCPeerIDHostApi.
NSObject<FlutterMessageCodec> *BFMCPeerIDHostApiGetCodec(void);

@protocol BFMCPeerIDHostApi
- (void)createInstanceId:(NSNumber *)instanceId displayName:(NSString *)displayName error:(FlutterError *_Nullable *_Nonnull)error;
- (void)disposeInstanceId:(NSNumber *)instanceId error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void BFMCPeerIDHostApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<BFMCPeerIDHostApi> *_Nullable api);

/// The codec used by BFMCSessionHostApi.
NSObject<FlutterMessageCodec> *BFMCSessionHostApiGetCodec(void);

@protocol BFMCSessionHostApi
- (void)createInstanceId:(NSNumber *)instanceId mcPeerIDInstanceId:(NSNumber *)mcPeerIDInstanceId encryptionPreference:(BFMCEncryptionPreferenceWrapper)encryptionPreference error:(FlutterError *_Nullable *_Nonnull)error;
- (void)disposeInstanceId:(NSNumber *)instanceId error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void BFMCSessionHostApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<BFMCSessionHostApi> *_Nullable api);

/// The codec used by BFMCNearbyServiceAdvertiserHostApi.
NSObject<FlutterMessageCodec> *BFMCNearbyServiceAdvertiserHostApiGetCodec(void);

@protocol BFMCNearbyServiceAdvertiserHostApi
- (void)createInstanceId:(NSNumber *)instanceId mcPeerIDInstanceId:(NSNumber *)mcPeerIDInstanceId info:(nullable NSDictionary<NSString *, NSString *> *)info serviceType:(NSString *)serviceType error:(FlutterError *_Nullable *_Nonnull)error;
- (void)disposeInstanceId:(NSNumber *)instanceId error:(FlutterError *_Nullable *_Nonnull)error;
- (void)registerDelegateInstanceId:(NSNumber *)instanceId error:(FlutterError *_Nullable *_Nonnull)error;
- (void)removeDelegateInstanceId:(NSNumber *)instanceId error:(FlutterError *_Nullable *_Nonnull)error;
- (void)startAdvertisingPeerInstanceId:(NSNumber *)instanceId error:(FlutterError *_Nullable *_Nonnull)error;
- (void)stopAdvertisingPeerInstanceId:(NSNumber *)instanceId error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void BFMCNearbyServiceAdvertiserHostApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<BFMCNearbyServiceAdvertiserHostApi> *_Nullable api);

/// The codec used by BFMCBrowserViewControllerHostApi.
NSObject<FlutterMessageCodec> *BFMCBrowserViewControllerHostApiGetCodec(void);

@protocol BFMCBrowserViewControllerHostApi
- (void)createInstanceId:(NSNumber *)instanceId peerId:(BFMCSessionWrapper *)peerId serviceType:(NSString *)serviceType error:(FlutterError *_Nullable *_Nonnull)error;
- (void)disposeInstanceId:(NSNumber *)instanceId error:(FlutterError *_Nullable *_Nonnull)error;
- (void)registerDelegateInstanceId:(NSNumber *)instanceId error:(FlutterError *_Nullable *_Nonnull)error;
- (void)removeDelegateInstanceId:(NSNumber *)instanceId error:(FlutterError *_Nullable *_Nonnull)error;
- (void)presentTheBrowserToViewControllerInstanceId:(NSNumber *)instanceId error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void BFMCBrowserViewControllerHostApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<BFMCBrowserViewControllerHostApi> *_Nullable api);

NS_ASSUME_NONNULL_END
